packages:
  - "web"

allowBuilds:
  '@mongodb-js/zstd': false
  core-js-pure: false
  esbuild: true
  node-liblzma: false
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - miniflare@4.20260617.1
  - wrangler@4.103.0
